site_name: Mes Cartes HA 🏠
site_url: https://maxence-csnt.github.io/Carte-Home-Assistant/
use_directory_urls: false

theme:
  name: material
  language: fr
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search

nav:
  - Accueil: index.md
  - 🛠️ Automatisation: 
      - Présentation: automatisation.md
      - Incendie 🔥: incendie.md
  - 📊 Dashboard: 
      - Présentation: dashboard.md
      - Humidité 💦: humidite.md
      - Boîte aux lettres 📬: boite-aux-lettres.md
