site_name: Mes Cartes HA 🏠
site_url: https://maxence-csnt.github.io/Carte-Home-Assistant/
use_directory_urls: false

# 1. Activation du style personnalisé
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: fr
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - announce.dismiss # Active la petite croix pour fermer le bandeau

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# 2. Le menu de navigation
nav:
  - Accueil: accueil.md
  - 📊 Dashboard: 
      - Présentation: dashboard.md
      - Humidité 💦 (Graphique): humidite (graphique).md
      - Humidité 💦: humidite.md
      - Boîte aux lettres 📬: boite-aux-lettres.md
      - Température 🌡️ (Graphique): temperature (graphique).md
      - Température 🌡️: temperature.md 
      - Imprimante 🖨️ (NOIR & BLANC): imprimante (noir & blanc).md
      - Réservoir à Eau 💧: reservoir-d-eau.md
      - Contact 🚪 (Porte): contact (porte).md
      - Détecteur de mouvement 💨: detecteur-de-mouvement.md
      - Éclairement ☀️: eclairement.md
      - Sonnette 🔔: sonnette.md
  - 🛠️ Automatisation: 
      - Présentation: automatisation.md
      - Incendie 🔥: incendie.md
  - 🎨 Espace créations: espace-creation.md
      - V1 ThGraf: v1-thgraf.md

# 3. Le bandeau d'annonce (IMPORTANT : bien aligné à gauche)
extra:
  announcement: >
    🚧 **SITE EN COURS DE CRÉATION**
